### PR TITLE
docs: add semantic-commit-msg

### PR DESCRIPTION
**Pull request by piyoki**
## Summary

As the title suggests. This tutorial helps beginner to write better git commit msg following the industry convention and standards.

### CODE REVIEW

**Comment by Cali0707** [comment]
Thanks for opening this PR @piyoki !!

Personally, I don't think that this should be a full "lesson" in the git-basics repo since the goal of this repository is really to be a minimal and approachable intro to fork based git development, building to and culminating with a PR in the final lesson. To me, conventional commits are a standard but non essential part of a git workflow, so having a full lesson on them in a beginner resource is too much. 

I do agree that mentioning conventional commits somewhere makes sense, maybe we can briefly mention in the lesson on commits that conventional commits are a common way to write commit messages and link to a website with more info there?

**Comment by piyoki** [comment]
> I do agree that mentioning conventional commits somewhere makes sense, maybe we can briefly mention in the lesson on commits that conventional commits are a common way to write commit messages and link to a website with more info there?

Sure no problem. How about moving this `md` to lession-3, and have a section/link for community users to dive into the topic?

**Comment by Cali0707** [comment]
Personally, I would just add one sentence in the paragraph about commit messages mentioning that conventional commits is a standard way to write commit messages and link to the conventional commits website

**Comment by piyoki** [comment]
> Personally, I would just add one sentence in the paragraph about commit messages mentioning that conventional commits is a standard way to write commit messages and link to the conventional commits website

Got it, resolved in https://github.com/UTOSS/git-basics/pull/86/commits/ec664cc2ffb8d0fd4f480e4fc4f01cd98e2c74b4 and https://github.com/UTOSS/git-basics/pull/86/commits/5b63ef6a67fe25472aab7c7c5736e3243ee3cc7f

**Review by Cali0707 — CHANGES_REQUESTED** [review]
A few nits, otherwise this is a lot more in line with what this repo is trying to do now, thanks for working on this @piyoki !

**Review by Cali0707 — APPROVED** [review]
LGTM

Thanks for working on this @piyoki

**Pull request merged**
